name: Build image
on: [push, pull_request]
env:
  MULLED_NAMESPACE: scgs
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        #python -m pip install git+https://git@github.com/galaxyproject/galaxy.git@dev#subdirectory=packages/util
        #python -m pip install git+https://git@github.com/galaxyproject/galaxy.git@dev#subdirectory=packages/tool_util
        python -m pip install galaxy-tool-util
    - run: docker --version
    - run: docker info
    - name: Build images
      run: |
        mulled-build-files --check-published --singularity --namespace $MULLED_NAMESPACE  build-and-test ./combinations --verbose
    - name: Upload images (if pushed to master branch)
      if: github.ref == 'refs/heads/main' && github.repository_owner == 'gongyh'
      env:
        INVOLUCRO_AUTH: "https://${{ secrets.MY_USER }}:${{ secrets.MY_PASSWORD }}@quay.io/v1/?email=${{ secrets.MY_EMAIL }}"
      run: |
        mulled-build-files --check-published --namespace $MULLED_NAMESPACE --oauth-token ${{ secrets.QUAY_OAUTH_TOKEN }} push ./combinations
